# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/matches', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Match. As you add validations to Match, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    FactoryBot.attributes_for(:match)
  end

  let(:invalid_attributes) do
    { status: nil, date: nil }
  end

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # MatchesController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) do
    {}
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Match.create! valid_attributes
      get matches_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      match = Match.create! valid_attributes
      get match_url(match), as: :json
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Match' do
        expect do
          post matches_url,
               params: { match: valid_attributes }, headers: valid_headers, as: :json
        end.to change(Match, :count).by(1)
      end

      it 'renders a JSON response with the new match' do
        post matches_url,
             params: { match: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Match' do
        expect do
          post matches_url,
               params: { match: invalid_attributes }, as: :json
        end.to change(Match, :count).by(0)
      end

      it 'renders a JSON response with errors for the new match' do
        post matches_url,
             params: { match: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        { status: :cancelled }
      end

      it 'updates the requested match' do
        match = Match.create! valid_attributes
        patch match_url(match),
              params: { match: new_attributes }, headers: valid_headers, as: :json
        match.reload
        expect(match.status).to eq('cancelled')
      end

      it 'renders a JSON response with the match' do
        match = Match.create! valid_attributes
        patch match_url(match),
              params: { match: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'renders a JSON response with errors for the match' do
        match = Match.create! valid_attributes
        patch match_url(match),
              params: { match: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested match' do
      match = Match.create! valid_attributes
      expect do
        delete match_url(match), headers: valid_headers, as: :json
      end.to change(Match, :count).by(-1)
    end
  end
end
